/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lmpcc_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {6, 6, 1};
static const casadi_int casadi_s2[3] = {6, 4, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};

/* lmpcc_model_expl_vde_forw:(i0[6],i1[6x6],i2[6x4],i3[4],i4[0])->(o0[6],o1[6x6],o2[6x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  if (res[0]!=0) res[0][0]=a3;
  a1=sin(a1);
  a3=(a0*a1);
  if (res[0]!=0) res[0][1]=a3;
  a3=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][2]=a3;
  if (res[0]!=0) res[0][3]=a0;
  a3=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][4]=a3;
  a3=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][5]=a3;
  a3=arg[1]? arg[1][2] : 0;
  a4=(a1*a3);
  a4=(a0*a4);
  a4=(-a4);
  if (res[1]!=0) res[1][0]=a4;
  a3=(a2*a3);
  a3=(a0*a3);
  if (res[1]!=0) res[1][1]=a3;
  a3=0.;
  if (res[1]!=0) res[1][2]=a3;
  if (res[1]!=0) res[1][3]=a3;
  if (res[1]!=0) res[1][4]=a3;
  if (res[1]!=0) res[1][5]=a3;
  a4=arg[1]? arg[1][8] : 0;
  a5=(a1*a4);
  a5=(a0*a5);
  a5=(-a5);
  if (res[1]!=0) res[1][6]=a5;
  a4=(a2*a4);
  a4=(a0*a4);
  if (res[1]!=0) res[1][7]=a4;
  if (res[1]!=0) res[1][8]=a3;
  if (res[1]!=0) res[1][9]=a3;
  if (res[1]!=0) res[1][10]=a3;
  if (res[1]!=0) res[1][11]=a3;
  a4=arg[1]? arg[1][14] : 0;
  a5=(a1*a4);
  a5=(a0*a5);
  a5=(-a5);
  if (res[1]!=0) res[1][12]=a5;
  a4=(a2*a4);
  a4=(a0*a4);
  if (res[1]!=0) res[1][13]=a4;
  if (res[1]!=0) res[1][14]=a3;
  if (res[1]!=0) res[1][15]=a3;
  if (res[1]!=0) res[1][16]=a3;
  if (res[1]!=0) res[1][17]=a3;
  a4=arg[1]? arg[1][20] : 0;
  a5=(a1*a4);
  a5=(a0*a5);
  a5=(-a5);
  if (res[1]!=0) res[1][18]=a5;
  a4=(a2*a4);
  a4=(a0*a4);
  if (res[1]!=0) res[1][19]=a4;
  if (res[1]!=0) res[1][20]=a3;
  if (res[1]!=0) res[1][21]=a3;
  if (res[1]!=0) res[1][22]=a3;
  if (res[1]!=0) res[1][23]=a3;
  a4=arg[1]? arg[1][26] : 0;
  a5=(a1*a4);
  a5=(a0*a5);
  a5=(-a5);
  if (res[1]!=0) res[1][24]=a5;
  a4=(a2*a4);
  a4=(a0*a4);
  if (res[1]!=0) res[1][25]=a4;
  if (res[1]!=0) res[1][26]=a3;
  if (res[1]!=0) res[1][27]=a3;
  if (res[1]!=0) res[1][28]=a3;
  if (res[1]!=0) res[1][29]=a3;
  a4=arg[1]? arg[1][32] : 0;
  a5=(a1*a4);
  a5=(a0*a5);
  a5=(-a5);
  if (res[1]!=0) res[1][30]=a5;
  a4=(a2*a4);
  a4=(a0*a4);
  if (res[1]!=0) res[1][31]=a4;
  if (res[1]!=0) res[1][32]=a3;
  if (res[1]!=0) res[1][33]=a3;
  if (res[1]!=0) res[1][34]=a3;
  if (res[1]!=0) res[1][35]=a3;
  a4=arg[2]? arg[2][2] : 0;
  a5=(a1*a4);
  a5=(a0*a5);
  a5=(a2-a5);
  if (res[2]!=0) res[2][0]=a5;
  a4=(a2*a4);
  a4=(a0*a4);
  a4=(a1+a4);
  if (res[2]!=0) res[2][1]=a4;
  if (res[2]!=0) res[2][2]=a3;
  a4=1.;
  if (res[2]!=0) res[2][3]=a4;
  if (res[2]!=0) res[2][4]=a3;
  if (res[2]!=0) res[2][5]=a3;
  a5=arg[2]? arg[2][8] : 0;
  a6=(a1*a5);
  a6=(a0*a6);
  a6=(-a6);
  if (res[2]!=0) res[2][6]=a6;
  a5=(a2*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][7]=a5;
  if (res[2]!=0) res[2][8]=a4;
  if (res[2]!=0) res[2][9]=a3;
  if (res[2]!=0) res[2][10]=a3;
  if (res[2]!=0) res[2][11]=a3;
  a5=arg[2]? arg[2][14] : 0;
  a6=(a1*a5);
  a6=(a0*a6);
  a6=(-a6);
  if (res[2]!=0) res[2][12]=a6;
  a5=(a2*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][13]=a5;
  if (res[2]!=0) res[2][14]=a3;
  if (res[2]!=0) res[2][15]=a3;
  if (res[2]!=0) res[2][16]=a4;
  if (res[2]!=0) res[2][17]=a3;
  a5=arg[2]? arg[2][20] : 0;
  a1=(a1*a5);
  a1=(a0*a1);
  a1=(-a1);
  if (res[2]!=0) res[2][18]=a1;
  a2=(a2*a5);
  a0=(a0*a2);
  if (res[2]!=0) res[2][19]=a0;
  if (res[2]!=0) res[2][20]=a3;
  if (res[2]!=0) res[2][21]=a3;
  if (res[2]!=0) res[2][22]=a3;
  if (res[2]!=0) res[2][23]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int lmpcc_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lmpcc_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lmpcc_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lmpcc_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lmpcc_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lmpcc_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lmpcc_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void lmpcc_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lmpcc_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int lmpcc_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real lmpcc_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lmpcc_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lmpcc_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lmpcc_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lmpcc_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lmpcc_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lmpcc_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
